services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      db:
        condition: service_healhty
    networks:
      - app-network
db:
  image: mysql:8.0
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: nodejsapp
  volumes:
    - db-data:/var/lib/mysql
    - ./db.sql:/docker-entrypoint-initdb.d/init.sql
  networks:
  - app-network
  healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 3

networks:
  app-network:

volumes:
  db-data: